# Generated by Django 5.2 on 2025-05-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("street_address", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("zip_code", models.CharField(max_length=10)),
                ("telephone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("date_of_survey", models.DateField()),
                (
                    "liked_most",
                    models.CharField(
                        choices=[
                            ("students", "Students"),
                            ("location", "Location"),
                            ("campus", "Campus"),
                            ("atmosphere", "Atmosphere"),
                            ("dorms", "Dorm Rooms"),
                            ("sports", "Sports"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "interested_via",
                    models.CharField(
                        choices=[
                            ("friends", "Friends"),
                            ("television", "Television"),
                            ("internet", "Internet"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "recommend",
                    models.CharField(
                        choices=[
                            ("very_likely", "Very Likely"),
                            ("likely", "Likely"),
                            ("unlikely", "Unlikely"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
