apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-survey-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-survey
  template:
    metadata:
      labels:
        app: django-survey
    spec:
      containers:
      - name: django-survey
        image: us-east1-docker.pkg.dev/swe645-extracredit/django-survey/django-backend:v4
        ports:
        - containerPort: 8000
        env:
        - name: DB_NAME
          value: "database_1"
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD
          value: "Admin123456"
        - name: DB_HOST
          value: "database-1.cd4ccgotiywz.us-east-1.rds.amazonaws.com"
